export const productCatalog = [
  {
    id: "heukson",
    name: "흙손",
    displayName: "흙손 가축분퇴비 분상",
    category: "유기농업 자재",
    form: "분상",
    material: "가축분퇴비 1등급",
    useType: "토양개량 및 작물생육용",
    packUnit: "20kg",
    usage: "20kg/10a 밑거름 20~150",
    guarantee: "유기물 30 이상",
    summary:
      "발효 후 3차 후숙 공정을 거친 분상 타입 제품으로, 토양 개량과 작물 생육 기반을 안정적으로 다지는 데 초점을 맞췄습니다.",
    cardSummary:
      "후숙 공정으로 안전성과 현장 적용성을 높인 분상형 가축분퇴비 제품입니다.",
    highlights: [
      "미생물 작용을 통해 병해충 부담을 낮추는 방향의 토양 환경 조성",
      "분상 타입이라 밑거름 운용과 넓은 면적 살포에 대응",
      "유기농업 자재군에 맞춘 토양 개량 중심 설계",
    ],
    cropTags: ["밑거름", "토양개량", "유기농업"],
    frontImage: "/image/heukson-front.jpeg",
    backImage: "/image/heukson-back.jpeg",
    sheetImage: "/image/heukson-sheet-300.jpg",
    badgeClass: "bg-[#173a12] text-[#d7ffbf]",
  },
  {
    id: "heukboyak",
    name: "흙보약",
    displayName: "흙보약 혼합유기질비료",
    category: "혼합유기질",
    form: "입상",
    material: "혼합유기질",
    useType: "토양개량 및 작물생육용",
    packUnit: "20kg",
    usage: "20kg/10a 밑거름 8~30",
    guarantee: "질소 3.4 · 인산 2.0 · 칼리 1.6 · 유기물 60 이상",
    summary:
      "과실의 당도와 착색, 토양 개량을 함께 고려한 입상형 혼합유기질비료입니다. 보수성, 보비력, 통기성 개선과 완효성 공급이 핵심입니다.",
    cardSummary:
      "당도와 착색, 토양 활력까지 함께 겨냥한 대표 혼합유기질비료입니다.",
    highlights: [
      "완효성 중심으로 전 생육기 동안 양분을 안정적으로 공급",
      "토양의 보수성, 보비력, 통기성 개선에 초점을 둔 설계",
      "토양 미생물 활동을 촉진해 토양 활력 증대를 지원",
    ],
    cropTags: ["과수", "채소류", "당도·착색"],
    frontImage: "/image/heukboyak-front.jpeg",
    backImage: "/image/heukboyak-back.jpeg",
    sheetImage: "/image/heukboyak-sheet-300.jpg",
    badgeClass: "bg-[#264d19] text-[#f6ffe8]",
  },
  {
    id: "mudeungsan",
    name: "무등산",
    displayName: "무등산 일반퇴비",
    category: "일반퇴비 1등급",
    form: "입상",
    material: "일반퇴비 1등급",
    useType: "토양개량 및 작물생육용",
    packUnit: "20kg",
    usage: "20kg/10a 밑거름 20~150",
    guarantee: "유기물 30 이상",
    summary:
      "유용미생물 증식과 토양 물리화학성 개선을 함께 노리는 일반퇴비 1등급 제품입니다. 속효성과 지효성의 균형으로 생육 전반을 받쳐줍니다.",
    cardSummary:
      "토양 구조 개선과 지속성 있는 양분 공급을 겨냥한 일반퇴비 제품입니다.",
    highlights: [
      "토양 물리화학성 개선과 유용미생물 증식에 초점",
      "생육 초기부터 후기까지 이어지는 지속형 양분 공급",
      "입상 타입으로 보관과 운용이 비교적 안정적인 편",
    ],
    cropTags: ["토양활력", "일반퇴비", "지속형 공급"],
    frontImage: "/image/mudeungsan-front.jpeg",
    backImage: "/image/mudeungsan-back.jpeg",
    sheetImage: "/image/mudeungsan-sheet-300.jpg",
    badgeClass: "bg-[#1d3327] text-[#d6f0d9]",
  },
] as const;
